Add alerting rules for DeadManSnitch
red-hat-data-services/odh-deployer pull request #112
Opened 2021-06-11 07:05 UTC by maulikjs

2021-06-11 07:18 UTC, maulikjs commented
/hold

2021-06-11 15:47 UTC, anishasthana requested changes

2021-06-11 15:47 UTC, anishasthana commented on monitoring/prometheus/prometheus.yaml
> +              description: RHODS monitoring and alerting pipeline is offline.
It should be the other way around right? The description of this alert is that the pipeline _is_ online.

2021-06-11 16:05 UTC, maulikjs commented on monitoring/prometheus/prometheus.yaml
> +              description: RHODS monitoring and alerting pipeline is offline.
ah right yes

2021-06-11 16:08 UTC, maulikjs commented on monitoring/prometheus/prometheus.yaml
> +              description: RHODS monitoring and alerting pipeline is offline.
updated

2021-06-11 16:47 UTC, anishasthana approved these changes
Changes look good, but I'd like for us to actually test it out. Do you have a deployment on stage OSD we can look at?
Can you also make a corresponding PR to https://gitlab.cee.redhat.com/croberts/olminstall for the dms secret creation so that we can have an easy way to continue installing RHODS?

2021-06-11 16:53 UTC, maulikjs commented
@anishasthana the secret is created as part of the add-on installation workflow. REF: https://gitlab.cee.redhat.com/service/managed-tenants/-/merge_requests/889

2021-06-11 16:56 UTC, anishasthana commented
Right, but can you create a dummy secret so we can test in non-OSD clusters internally.

2021-06-11 18:21 UTC, maulikjs commented
Ah ok raising a MR then

2021-06-14 18:16 UTC, crobby approved these changes
seems to work now, lgtm

2021-06-14 18:28 UTC, crobby approved these changes
Seems to be working

2021-06-14 18:31 UTC, maulikjs commented
/hold

2021-06-14 18:35 UTC, maulikjs commented
/unhold

2021-06-15 09:00 UTC, merged