Email template notifications
red-hat-data-services/odh-deployer pull request #147
Opened 2021-08-16 21:56 UTC by lucferbux

## Related Issues and Dependencies

[RHODS-852](https://issues.redhat.com/browse/RHODS-852)

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

* Added template folder to create custom mail notification

## Description

Based on the work of [implementing user notifications](https://issues.redhat.com/browse/RHODS-336), we are using [prometheus' built in alert management](https://prometheus.io/docs/alerting/latest/alertmanager/) to trigger email alerts.

## Testing

[WIP]

## UX Changes

<img width="599" alt="Screenshot 2021-08-16 at 23 51 27" src="https://user-images.githubusercontent.com/16117276/129633933-a5cc3c34-fa87-401f-9747-83f625723cd3.png">

2021-08-17 08:44 UTC, lucferbux commented
@maulikjs and I still need to make some adjustments to the PR.

2021-08-23 09:46 UTC, lucferbux commented
@maulikjs @anishasthana @gmfrasca I've updated the description to test the issue, we currently have to figure out one more thing:

- The embedded image inside the email needs a URL just like this one -> https://www.redhat.com/cms/managed-files/Logo-Red_Hat-OpenShift-A-Standard-RGB.png in order to be displayed in gmail. We need a way to store the image in a public URL inside one of our CDNs.
- We should delete or review the [repeated interval](https://github.com/lucferbux/odh-deployer/blob/prometheus_mail_notifications/monitoring/prometheus/prometheus.yaml#L1427), right now is set to 2 mins to test out the feature .

2021-08-23 15:30 UTC, maulikjs commented on monitoring/prometheus/prometheus.yaml
> +      - match:
remove this block of code

2021-08-23 15:31 UTC, lucferbux commented on monitoring/prometheus/prometheus.yaml
> +      - match:
👍

2021-08-23 15:34 UTC, anishasthana requested changes
Can you rebase on master and squash commits? Something seems odd about your commits in this PR

2021-08-23 17:38 UTC, lucferbux commented
> Can you rebase on master and squash commits? Something seems odd about your commits in this PR
Gonna do that once all changes are commited.

2021-08-23 17:40 UTC, lucferbux commented
Ok, so right now there are two things to discuss:

- [Which subject does the emails need](https://github.com/lucferbux/odh-deployer/blob/prometheus_mail_notifications/monitoring/prometheus/prometheus.yaml#L1470)
- [The img tag](https://github.com/lucferbux/odh-deployer/blob/prometheus_mail_notifications/monitoring/prometheus/prometheus.yaml#L1344)

Once we have that sorted out, it will be ready

2021-08-24 12:03 UTC, lucferbux commented
> Can you rebase on master and squash commits? Something seems odd about your commits in this PR

Done, rebase from master and squashed all the commits, I'm gonna request your review again

2021-08-24 21:19 UTC, anishasthana reviewed
I think this looks good. The only remaining question is about the image

2021-08-25 13:41 UTC, lucferbux commented
> I think this looks good. The only remaining question is about the image

Image is not hosted on the repo. Updating the info.

2021-08-25 13:42 UTC, anishasthana commented
![image](https://user-images.githubusercontent.com/6526150/130801480-1b751909-a975-4807-b6f1-ae07fd96caaf.png)

2021-08-25 14:09 UTC, maulikjs approved these changes

2021-08-25 14:37 UTC, merged