WIP: RBAC for dedicated-admins in select namespaces if installed on OSD
red-hat-data-services/odh-deployer pull request #148
Opened 2021-08-17 06:44 UTC by gmfrasca

- Grant CRUD for CMs, ISs, BCs, Builds and Secrets on the applications and JH notebooks namespaces if install target is OpenShift Dedicated
- dedicated-admins group does not exist if not on OSD, so don't install otherwise

2021-08-17 17:53 UTC, anishasthana requested changes
Can you link to the related JIRA issue in the PR?

2021-08-17 18:05 UTC, gmfrasca commented
PR: https://issues.redhat.com/browse/RHODS-1590

2021-08-17 19:02 UTC, anishasthana reviewed
Is this deployed anywhere/ available as a built image?

2021-08-18 15:10 UTC, anishasthana approved these changes
I have verified that the roles and rolebindings are created. They also granted enough permissions to dedicated-admins that we were expecting. 

This should only be merged in after the changes in https://github.com/red-hat-data-services/odh-manifests/pull/144 have made their way into the opendatahub-operator repo.

2021-08-18 15:15 UTC, merged