Add oauth proxy to prometheus and scale down grafana
red-hat-data-services/odh-deployer pull request #20
Opened 2021-02-14 02:33 UTC by maulikjs

2021-02-14 16:46 UTC, anishasthana commented on grafana.yaml
> +  replicas: 1
any reason we're scaling it down? I thought HA is always desirable.

2021-02-14 16:47 UTC, anishasthana commented on prometheus.yaml
> +        image: quay.io/openshift/origin-oauth-proxy:4.6.0
Could we just use the sme image as what is used for Grafana?

2021-02-14 16:47 UTC, anishasthana commented on prometheus.yaml
> +  session_secret: "uTgRq5qg4GlwsIXrAePXjTqz5DBhKqhERfGVOmyS"
We'll need to generate this "live" eventually. I'm writing some bash to hopefully make it easier.

2021-02-14 16:48 UTC, anishasthana requested changes

2021-02-14 16:48 UTC, anishasthana commented on prometheus.yaml
> +# ---
Just leave this commented bit out for now.

2021-02-14 18:48 UTC, maulikjs commented on grafana.yaml
> +  replicas: 1
Well, this is more of a load balancing thing rather than an HA thing at least that's what it was for telemetry given the number of users fetching dashboards. I assume we arent expecting that heavy a workload also since they will all be going to the same Prometheus it doesn't really help.

2021-02-14 18:48 UTC, maulikjs commented on prometheus.yaml
> +  session_secret: "uTgRq5qg4GlwsIXrAePXjTqz5DBhKqhERfGVOmyS"
👍 yup yup

2021-02-14 18:49 UTC, maulikjs commented on prometheus.yaml
> +  session_secret: "uTgRq5qg4GlwsIXrAePXjTqz5DBhKqhERfGVOmyS"
I think we already have the bash scripts for it in our dh-monitoring repo.

2021-02-14 18:49 UTC, maulikjs commented on prometheus.yaml
> +        image: quay.io/openshift/origin-oauth-proxy:4.6.0
yeah, I didnt realize there was a newer version out there.

2021-02-15 14:45 UTC, anishasthana commented on grafana.yaml
> +  replicas: 1
Well having at least one replica is important in case the node grafana is running on has some issues. We can lower it to two if you really want.

2021-02-15 16:46 UTC, anishasthana commented on prometheus.yaml
> +        - -http-address=
if the entry is empty should we just remove this?

2021-02-15 17:10 UTC, anishasthana reviewed
We can merge the changes in once my last comment is resolved/rejected.

2021-02-15 17:41 UTC, anishasthana approved these changes

2021-02-15 17:41 UTC, merged

2021-02-15 17:43 UTC, crobby commented
Can someone also fire-up a cherry-pick of this to the v1.0.0 branch?  Thanks