add jupyterhub-idle-culler
red-hat-data-services/odh-deployer pull request #216
Opened 2022-03-09 13:31 UTC by maroroman

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [ ] The developer has manually tested the changes and verified that the changes work.

2022-03-09 21:05 UTC, LaVLaS commented on jupyterhub/jupyterhub-configmap.yaml
> +  culler_timeout: "31536000 " # 1 year
Should the default timeout be 1 year when it was previously 3 days?

2022-03-15 12:17 UTC, maroroman commented on jupyterhub/jupyterhub-configmap.yaml
> +  culler_timeout: "31536000 " # 1 year
As per comments here: https://issues.redhat.com/browse/RHODS-2324

The default cannot be set to infinity (no culling) so we decided to provide a high starting value for "no culling" so that notebooks are culled only if the administrator wants them to and the culler is enabled by default.

2022-03-29 15:39 UTC, crobby requested changes
I will try and get a live build together for this, but I don't think it will work.  The KfDef, I think, will need to look like the change tried out here:  https://github.com/crobby/odh-deployer/commit/8dfd193b3115fb8fa47ed07e2a3e4abcc9e6cd9b

2022-04-04 13:21 UTC, crobby commented
Obviated by:  https://github.com/red-hat-data-services/odh-deployer/pull/224

2022-04-05 15:14 UTC, crobby commented
Needs a rebase

2022-04-13 14:41 UTC, crobby approved these changes

2022-04-22 11:57 UTC, maroroman commented
Replaced by #228

2022-04-22 11:57 UTC, closed without merging