Restart prometheus
red-hat-data-services/odh-deployer pull request #226
Opened 2022-04-04 16:19 UTC by anishasthana

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-1974
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

2022-04-09 10:43 UTC, anishasthana commented
Refer to https://github.com/red-hat-data-services/opendatahub-operator/pull/133 for the latest live builds.

2022-04-11 11:39 UTC, crobby requested changes
I had a problem when running this...I think it's just targeting the old filenames.  Please take a look

2022-04-11 11:39 UTC, crobby commented on deploy.sh
> +sed -i "s/<prometheus_config_hash>/$prometheus_config/g" monitoring/prometheus/prometheus.yaml
When I run this, I get:  sed: -e expression #1, char 29: unknown option to `s'

Any chance this needs to reference prometheus-configs.yaml?

2022-04-11 11:39 UTC, crobby commented on deploy.sh
> +sed -i "s/<alertmanager_config_hash>/$alertmanager_config/g" monitoring/prometheus/prometheus.yaml
possible target file name change here too?

2022-04-11 12:06 UTC, anishasthana commented on deploy.sh
> +sed -i "s/<prometheus_config_hash>/$prometheus_config/g" monitoring/prometheus/prometheus.yaml
Indeed. I messed up part of the rebase from Lucas's PR :(

2022-04-12 09:18 UTC, lucferbux approved these changes
/lgtm
It works.

2022-04-14 08:10 UTC, jgarciao commented
lgtm too (tested livebuild a couple of days ago)

2022-04-14 09:00 UTC, merged