Update OSD check to use an OpenShift configmap
red-hat-data-services/odh-deployer pull request #227
Opened 2022-04-05 18:14 UTC by anishasthana

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3454
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

2022-04-05 18:46 UTC, anishasthana commented
@pablofelix  Live build is available at quay.io/anishasthana/rhods-operator-live-catalog:1.90.0-3454. It's upgrading from `1.8.0-14` as there isn't an official 1.9.0 build yet.

2022-04-06 10:43 UTC, crobby commented on deploy.sh
> +  # On AWS OpenShift Dedicated, deploy with CRO
Can we maybe log a message here of some sort so it can be obvious?

2022-04-06 10:50 UTC, crobby requested changes
I think a log noting which env, AWS or "not", would help....maybe bonus points for the log entry indicating what else that will mean (the AWS DB getting created instead of local)

2022-04-06 11:20 UTC, crobby approved these changes
/lgtm

2022-04-06 14:59 UTC, anishasthana commented
quay.io/anishasthana/rhods-operator-live-catalog:1.92.0-3454 is the livebuild with the additional logging, in case anyone is interested!

2022-04-07 14:29 UTC, accorvin commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
I worry that this, as it, might eventually bite us when we look to deploy on other cloud providers. Can we update this to somehow fail if we're running on something other than PSI or AWS?

2022-04-07 17:38 UTC, anishasthana commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
(it's not a hard check to implement) I'm not sure it's actually worth it. The way I see it, right now AWS is a special case with requiring CRO, and PSI is a "base" case. If we need to deploy on GCP, or ARO, I imagine it'd be as simple as specifying an additional if-else.

2022-04-07 17:39 UTC, accorvin commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
What I'm saying is that if we forget to come back and add that additional if-else (seems like a very easy thing to forget) then this will get deployed in GCP without HA.

2022-04-07 17:57 UTC, LaVLaS commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
> What I'm saying is that if we forget to come back and add that additional if-else (seems like a very easy thing to forget) then this will get deployed in GCP without HA.

In that scenario, wouldn't HA support be part of the GCP "on-boarding" development process?  If it fails then we would "un-break" RHODS on GCP before we could start working on replacing the postgres `jupyterhub-db`

2022-04-07 17:59 UTC, accorvin commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
Yes that's true. I'm probably being overly cautious in this. I'll defer to you all if you're good with this plan.

2022-04-07 18:02 UTC, anishasthana commented on deploy.sh
> +if [ "$(oc get infrastructure cluster -o jsonpath='{.spec.platformSpec.type}')" = "AWS" ]; then
Bah. I see your point. Updated.

2022-04-07 18:42 UTC, anishasthana commented
Hopefully final live build: quay.io/anishasthana/rhods-operator-live-catalog:1.97.0-3454

2022-04-07 18:47 UTC, accorvin commented
I'm spinning up a ROSA cluster to test this on now.

2022-04-07 19:16 UTC, accorvin commented
I see this line in the odh-deployer pod on my ROSA cluster: ```INFO: Deploying on AWS. Creating CRO for deployment of RDS Instance```
So I think it's good.

2022-04-07 20:13 UTC, accorvin commented
Another update: I see the following on a PSI OSIA cluster:
```
INFO: Deploying on PSI. Creating local database
```

I can confirm that the CRO pod does not get created in PSI, and the PostgreSQL pod does.

So, everything looks good on both PSI and ROSA.

2022-04-08 08:00 UTC, lucferbux approved these changes
/lgtm

2022-04-08 08:00 UTC, lucferbux commented
Checked on PSI, works great.

2022-04-13 14:40 UTC, merged