Creating a CONTRIBUTING.md
red-hat-data-services/odh-deployer pull request #229
Opened 2022-04-27 17:49 UTC by DharmitD

Signed-off-by: Dharmit Dalvi <ddalvi@redhat.com>

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-3584
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [ ] The developer has manually tested the changes and verified that the changes work.

2022-04-27 18:59 UTC, lucferbux approved these changes
/lgtm

2022-04-28 19:12 UTC, anishasthana requested changes

2022-04-28 19:12 UTC, anishasthana commented on CONTRIBUTING.md
> +### How to contribute code to odh-deployer
Can you add a note here saying who the primary QE contact is for the repo?

2022-04-28 19:12 UTC, anishasthana commented on CONTRIBUTING.md
> +### Testing the PR
Can you add a note here on quick testing? When I'm quickly iterating on changes what I like doing is manually running the deploy script from the terminal.  This way I don't waste time building a new image every time. Definitely helps in that initial rapid iteration phase.

2022-04-29 00:46 UTC, DharmitD commented on CONTRIBUTING.md
> +### How to contribute code to odh-deployer
Updated the doc to include names of primary QE contacts.

2022-04-29 00:46 UTC, DharmitD commented on CONTRIBUTING.md
> +### Testing the PR
Updated the doc to mention this process of testing manually.

2022-04-29 00:48 UTC, DharmitD commented
Also updated the PR template to remove check box for adding an entry to the build doc, as we no longer require an entry to be created in the build doc.

2022-04-29 14:31 UTC, anishasthana approved these changes

2022-04-29 14:31 UTC, merged