Update prometheus rhods_aggregate_availability metric
red-hat-data-services/odh-deployer pull request #235
Opened 2022-06-17 07:28 UTC by atheo89

Updated the rhods_aggregate_availability metric to include a label indicating the availability of each component over time. 

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-4229
- [x] The Jira story is acked
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

2022-06-17 12:05 UTC, lucferbux commented
@gmfrasca i think we got something, please, check this out to see how it went, thanks!

2022-06-17 13:01 UTC, gmfrasca commented on monitoring/prometheus/prometheus-configs.yaml
> +        - expr: min(probe_success offset 5h) by (instance) or label_replace(min(probe_success offset 5h), "instance", "combined", "", "")
I don't think you want those `offset` s in there.... they're usually just for testing against historical data

2022-06-17 13:11 UTC, gmfrasca commented on monitoring/prometheus/prometheus-configs.yaml
> +        - expr: min(probe_success offset 5h) by (instance) or label_replace(min(probe_success offset 5h), "instance", "combined", "", "")
I haven't tested so perhaps this works, but does having dst_label and dst_regex (the 4th and 5th params for label_replace) replace more than just the original instance label?   Probably moot point now but I wonder if it will have implications if anyone builds on top of this.  so tl,dr: maybe just replace the instance label?

2022-06-17 13:40 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> +        - expr: min(probe_success offset 5h) by (instance) or label_replace(min(probe_success offset 5h), "instance", "combined", "", "")
Hi Giulio, thanks for the review. I am going to delete offset, but I am not sure if I have to change **instance -> component:** min(probe_success) by (instance) or label_replace(min(probe_success), "**instance**", "combined", "", "") to **component** for example.

2022-06-17 13:54 UTC, gmfrasca commented on monitoring/prometheus/prometheus-configs.yaml
> +        - expr: min(probe_success offset 5h) by (instance) or label_replace(min(probe_success offset 5h), "instance", "combined", "", "")
so going of the corresponding ticket, it looks like the aggregated item just needs to be consistent with the 'split' ones, which appear to be using `instance`.  you could probably relabel _all_ of them to rename `instance` to `component`, but that's probably more work than necessary.

2022-06-17 17:04 UTC, gmfrasca reviewed
/lgtm

2022-06-17 17:05 UTC, gmfrasca approved these changes

2022-07-07 15:52 UTC, anishasthana requested changes

2022-07-07 15:52 UTC, anishasthana commented on monitoring/prometheus/prometheus-configs.yaml
> +
Can you fix this whitespace that was added?

2022-07-13 13:22 UTC, anishasthana requested changes

2022-07-13 13:22 UTC, anishasthana commented on monitoring/prometheus/prometheus-configs.yaml
> +      scrape_interval: 10s
If we don't care about further improving traefik accuracy why are we updating the scrape interval here?

2022-07-13 13:30 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> +      scrape_interval: 10s
You are right, maybe I should remove the scape_interval completely from there because it wasn't before. May I proceed to this deletion?

2022-07-13 17:33 UTC, anishasthana approved these changes

2022-07-19 07:15 UTC, pablofelix commented
lgtm

2022-07-27 09:45 UTC, pablofelix approved these changes
lgtm

2022-07-29 09:00 UTC, merged