Instructions about for to use the tide plugin (Openshift CI) for auto merging
red-hat-data-services/odh-deployer pull request #254
Opened 2022-08-04 14:44 UTC by atheo89

Added instructions about how to use tide plugin of openshift ci into contribution.md file

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2769, https://issues.redhat.com/browse/RHODS-3396
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2022-08-04 14:51 UTC, crobby requested changes

2022-08-04 14:51 UTC, crobby commented on CONTRIBUTING.md
> +- When your PR is ready to be tested comment a Quality Engineer using the label '/cc qe_github_user'. Here is a list with QE contacts [pablofelix, tarukumar]. When the test is done you should get an
Slightly awkward wording....maybe something like this...
"When your PR is ready to be tested, indicate so by adding `/cc qe_github_user` in a comment".  This will summon a Quality Engineer............

2022-08-05 16:48 UTC, anishasthana requested changes
1. Can the commits be squashed?
2. Additionally, I would update the commit message to be something like
`Update CONTRIBUTING.md to account for OpenShift CI`

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- And finaly when the PR has been tested from a QE, you should get an `qe-approved` tag (see [the OWNERS_ALIASES file of the repo](https://github.com/red-hat-data-services/odh-deployer/blob/main/OWNE
I'd add a sub point here saying that QE can use the `/label qe-approved` command to add their label too

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- And finaly when the PR has been tested from a QE, you should get an `qe-approved` tag (see [the OWNERS_ALIASES file of the repo](https://github.com/red-hat-data-services/odh-deployer/blob/main/OWNE
```suggestion
-  A `qe-approved` label has been added by a QE member
```

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- An `/approved` tag from an approver
```suggestion
- An `approved` label has been added by an approver
```

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- Be sure that you got a `/lgtm` tag from a reviewer
```suggestion
- A `lgtm` label has been added by a reviewer
```

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- We are using the tide plugin (Openshift CI), so please follow the next steps
```suggestion
- We are using OpenShift CI to control merges to the deployer repository. PRs will automatically be merged when the following conditions are met
```

2022-08-05 16:48 UTC, anishasthana commented on CONTRIBUTING.md
> +- Your PR is ready to be auto-merged
```suggestion
- The [OWNERS_ALIASES](https://github.com/red-hat-data-services/odh-deployer/blob/main/OWNERS_ALIASES)  file of the repository has a list of the people who can review, approve, and qe-approve PRs.
```

2022-08-05 16:48 UTC, anishasthana commented on OWNERS_ALIASES
> +    - crobby
Can we organize these lists in alphabetical order

2022-08-08 12:32 UTC, atheo89 commented
Thank you for your feedback and for noticing this points! I have updated the PR with the last comments.

2022-08-08 18:01 UTC, anishasthana approved these changes
/lgtm

2022-08-09 07:14 UTC, pablofelix commented
/qe-approved

2022-08-09 07:14 UTC, pablofelix approved these changes
/qe-approved

2022-08-09 07:17 UTC, pablofelix approved these changes
/lgtm

2022-08-10 11:33 UTC, samuelvl requested changes

2022-08-10 11:33 UTC, samuelvl commented on CONTRIBUTING.md
> +- The [OWNERS_ALIASES](https://github.com/red-hat-data-services/odh-deployer/blob/main/OWNERS_ALIASES) file of the repository has a list of the people who can review, approve, and qe-approve PRs.
Can you indent 2nd level items? 

- We are using OpenShift CI to control merges to the deployer repository. PRs will automatically be merged when the following conditions are met:
  - Item 1
  - Item 2
  - Item 3
  - etc

2022-08-10 11:43 UTC, atheo89 commented on CONTRIBUTING.md
> +- The [OWNERS_ALIASES](https://github.com/red-hat-data-services/odh-deployer/blob/main/OWNERS_ALIASES) file of the repository has a list of the people who can review, approve, and qe-approve PRs.
Thanks for noticing that, looks better now.

2022-08-10 11:58 UTC, samuelvl approved these changes

2022-08-10 16:44 UTC, atheo89 commented
/uncc @crobby due to `No longer valid.`

2022-08-10 16:45 UTC, merged