Update rhods prometheus stack according the kfnbc migration
red-hat-data-services/odh-deployer pull request #256
Opened 2022-08-10 15:25 UTC by atheo89

This PR cleans up the obsolete monitoring targets, alerts and recording rules from Prometheus configuration

## Description
Applied the following changes:

- Removed Traefik
- Remove Jupyterhub and JupyterhubDB (WIP)
- Add monitoring target for Jupyter notebook spawner page (WIP)

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-4765
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2022-08-11 07:49 UTC, atheo89 commented
Adding in /cc @Samu to be aware for the PRs that deal with the changes on the monitoring stack

2022-08-11 10:46 UTC, atheo89 commented
Some notes and thoughts regarding the third point of this PR `Add monitoring target for Jupyter notebook spawner page`

**Case 1:**
 Adding the URLs 
`- rhods-dashboard-redhat-ods-applications.apps.atheodor.dev.datahub.redhat.com/notebookController/spawner` or 
`- rhods-dashboard-redhat-ods-applications.apps.atheodor.dev.datahub.redhat.com/notebookController`
as targets into the job: `user_facing_endpoints_status` and alongside deleting the ServiceAccounts `notebook-controller-service-account`, `odh-notebook-controller-manager` and `rhods-dashboard` (Having the operator scaled down) I don't see any downtime on the targets via `rhods_aggregate_availability` metric. (The scraping of the targets is UP)

**Case 2:**
Adding the URLs 
`- rhods-dashboard-redhat-ods-applications.apps.atheodor.dev.datahub.redhat.com/notebookController/spawner` or 
`- rhods-dashboard-redhat-ods-applications.apps.atheodor.dev.datahub.redhat.com/notebookController`
as targets into the job: `user_facing_endpoints_status` and stop notebook server (via rhods dashboard) I don't see any downtime again through `rhods_aggregate_availability` metric.

I believe the reason that we don't see any downtime while we scrape these targets is that the kfnbc spawner is embedded on rhods dashboard.

Any alternative thoughts regarding how to scrape or not the notebook spawner?

2022-08-11 12:21 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
> -          record: rhods_total_users
I know that the BU watches this metric pretty closely to understand how much notebooks are being used, so we should try to retain this measurement if possible. Do you know if KFNBC has any built in metrics that track the number of users?

2022-08-11 12:21 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
>          - alert: RHODS Probe Success Burn Rate
MT-SRE has requested that we split this alert up so that the alert name is more specific to the service that is alerting. In its current state, this alert will fire for failures on both the RHODS dashboard and the notebook spawner.

I think we need to copy this alert block and then change the expressions so that one fires only for the dashboard and the other fires only for the notebook spawner.

2022-08-11 12:58 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> -          record: rhods_total_users
Maybe this one could work `runningNotebooks` https://github.com/opendatahub-io/kubeflow/blob/321ead60e215a3eb9d579a1e3de657150606e24d/components/notebook-controller/pkg/metrics/metrics.go#L15

2022-08-11 14:03 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
> -          record: rhods_total_users
I fear that that's the number of actively running users (which is still a very useful metric to have - we have some metrics around this already which probably need to be updated). To get the total number of all time users we may need to generate it from something else, perhaps the number of PVCs matching the right name pattern or something like that.

2022-08-19 09:33 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
>          - alert: RHODS Probe Success Burn Rate
Added the monitoring target for Jupyter notebook spawner page, and I updated the alert rule to fire the notebook spawner. 
relevant commits:

- [Added monitoring target for Jupyter notebook spawner page](https://github.com/red-hat-data-services/odh-deployer/pull/256/commits/03e964a863a47ecfaa422400ca1ef8935ef1ab3a)
- [Added alert block that fires the notebook spawner](https://github.com/red-hat-data-services/odh-deployer/pull/256/commits/d6c59a9e92058df1d444d6ebd086531f42412682)

2022-08-19 14:59 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
> +
nit: looks like you're adding trailing whitespace here. Is that deliberate?

2022-08-19 14:59 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
> +            sum(probe_success:burnrate30m{name=~"rhods-dashboard"}) by (name) > (6.00 * (1-0.99950))
For all of the alerting rules where you're making this change, the alerts are named `RHODS Probe Success Burn Rate`. Since these are now specific to the dashboard, can you change the name to `RHODS Dashboard Probe Success Burn Rate`? 

This change:
1. Makes these alert names consistent with the changes you've made above for the jupyter alerts
2. Satisfies MT-SRE's request to make the alert names more descriptive.

2022-08-22 07:07 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> +
Yep, it separates visually the ` SLOs - RHODS Operator` rules from  `Usage Metrics`

2022-08-22 07:16 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> +            sum(probe_success:burnrate30m{name=~"rhods-dashboard"}) by (name) > (6.00 * (1-0.99950))
Thanks for noticing that! Changed.

2022-08-22 12:18 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
> +
I'm not talking about the empty line, but rather the fact that the new line includes 4 spaces on it. (good yaml syntax dictates that blank lines contain no whitespace characters e.g. spaces or tabs)

2022-08-22 12:20 UTC, accorvin commented
@atheo89 these changes look good to me (other than the small whitespace nit). Do you have a live build I can test with?

2022-08-22 12:25 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
> +
Ahhh ok, the spaces added by vs code. I deleted them and kept only the newline

2022-08-22 12:31 UTC, atheo89 commented
@accorvin today, we had a discussion with @samuelvl about the live build. He is going to bunch all the monitoring changes together and he will provide a live build. Once it will be ready we will add the link for the live build.

2022-08-23 12:47 UTC, anishasthana commented
@atheo89 the prometheus stack init container will also need to be updated to account for traefik proxy
https://github.com/red-hat-data-services/odh-deployer/blob/main/monitoring/prometheus/prometheus.yaml#L22-L35

2022-08-23 12:52 UTC, atheo89 commented
@anishasthana, I should remove the command, right?

2022-08-23 13:00 UTC, anishasthana commented
It would be better to update it so that prometheus is waiting for one of the notebook controller pods to come up.

2022-08-24 10:37 UTC, atheo89 commented
**Note**: Added on this PR the changes for the fault firing of the kfnbc alerts, and I closed the old one.  https://github.com/red-hat-data-services/odh-deployer/pull/255

2022-08-24 14:51 UTC, jgarciao requested changes

2022-08-24 14:51 UTC, jgarciao commented on monitoring/prometheus/prometheus-configs.yaml
>              triage: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/blob/main/RHODS/JupyterHub/rhods-probe-success-burn-rate.md"
triage url should be updated for kubeflow

2022-08-25 09:24 UTC, atheo89 commented on monitoring/prometheus/prometheus-configs.yaml
>              triage: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/blob/main/RHODS/JupyterHub/rhods-probe-success-burn-rate.md"
Updated

2022-08-25 15:04 UTC, accorvin commented
A new live build with these changes is available at quay.io/accorvin/rhods-operator-live-catalog:1.0.0-rhods-4765

2022-08-25 15:51 UTC, accorvin commented
@atheo89 I'm getting an error in the deployer init container:
```
sed: -e expression #1, char 101: unknown option to `s'
```

2022-08-25 15:57 UTC, accorvin commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
Is there an extra `'` character here right after `$NOTEBOOK_SUFFIX` ?

2022-08-25 16:15 UTC, accorvin commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
Nope, this was not the issue.

2022-08-25 16:16 UTC, accorvin commented
I believe I've found the problem that was causing the deploy script to fail. I've added https://github.com/red-hat-data-services/odh-deployer/pull/256/commits/b9eb01445121d4315bc2833829d65ae742d37be5 with a fix and am building a new live image now.

2022-08-25 16:30 UTC, jgarciao requested changes

2022-08-25 16:30 UTC, jgarciao commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
If severity = warning SRe won't be paged if notebook controller is down for more than  5 minutes. Should this be critical instead?

2022-08-25 16:30 UTC, jgarciao commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
If severity = warning SRe won't be paged if notebook controller is down for more than  5 minutes. Should this be critical instead?

2022-08-25 16:30 UTC, jgarciao commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
This variable contains the route to the new spawner page (e.g. https://rhods-dashboard-redhat-ods-applications.apps.qeaisrhods-mon.XXXX.s1.devshift.org/notebookController/spawner), that is used in the alert _RHODS Jupyter Probe Success Burn Rate_

What I have experimented in the livebuild is that, if the _Kubeflow notebook controller_ pod and the _ODH notebook controller_ pod are not running, the alert _RHODS Jupyter Probe Success Burn Rate_ does not fire.

I believe the reason is that https://rhods-dashboard-redhat-ods-applications.apps.qeaisrhods-mon.XXXX.s1.devshift.org/notebookController/spawner renders the page correctly (returning HTTP 200) even if those pods are not running

What happens in that situation is that, when you try to spawn a notebook, you get this error:
![error-spawning-notebook-when-pods-are-not-running](https://user-images.githubusercontent.com/66894/186718617-09a365b3-0ab7-4323-8b82-720db93a3e8b.png)

So, I don't know if the alert _RHODS Jupyter Probe Success Burn Rate_ is useful with this implementation, having already  _RHODS Dashboard Probe Success Burn Rate_

2022-08-25 17:15 UTC, accorvin commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
@lucferbux @andrewballantyne this to me seems like functionality that should perhaps change on the notebook spawner page. If the backend dependencies aren't met, does it make sense for the spawner page to generate a 200 status code when you load it?

2022-08-25 17:19 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
When we met with SRE a few weeks ago to come up with the plan for monitoring KFNBC, we agreed that we would make this a warning level error while/until we determine how the alert behaves in production. The thought was that we should be able to rely on kubernetes functionality to ensure that the pod is always running, so we likely don't need any alert for this. We weren't 100% confident of this decision though so a warning alert seemed like a good compromise.

2022-08-25 17:19 UTC, accorvin commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
When we met with SRE a few weeks ago to come up with the plan for monitoring KFNBC, we agreed that we would make this a warning level error while/until we determine how the alert behaves in production. The thought was that we should be able to rely on kubernetes functionality to ensure that the pod is always running, so we likely don't need any alert for this. We weren't 100% confident of this decision though so a warning alert seemed like a good compromise.

2022-08-25 17:20 UTC, accorvin commented
The issue with the odh deployer init container failing has been resolved by my latest change (this change is available in the live build, I pushed the new version to the same tag).

I'm seeing an issue now where the probes are getting 403 errors. I'm investigating why that is happening.

2022-08-25 17:34 UTC, accorvin commented
Update: I found that the opendatahub-operator container in my live build did not properly include the changes from https://github.com/red-hat-data-services/odh-manifests/pull/231

I'm generating a new live build that resolves that and will post with the status of my testing.

2022-08-25 18:18 UTC, accorvin commented
Update: this looks to be working correctly now with the latest version of my live build

2022-08-25 19:14 UTC, cfchase commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
I don't think we want the dashboard in the business of checking for status of backend controllers.  I think we'd do a poor job of it since we can't really anticipate the ways in which it fails for any given controller.  Honestly, I think this UX is pretty good the way it is since it's properly conveying an error from the notebook spawn.

2022-08-26 02:57 UTC, LaVLaS commented
Rhods livebuild for these changes with KFNBC and migration script: [quay.io/llasmith/rhods-operator-live-catalog:1.16.0-dashboard-kfnbc](http://quay.io/llasmith/rhods-operator-live-catalog:1.16.0-dashboard-kfnbc)

2022-08-26 11:28 UTC, jgarciao commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
Ok, it makes sense. Thanks!

2022-08-26 11:29 UTC, jgarciao commented on monitoring/prometheus/prometheus-configs.yaml
>              severity: warning
Ok, it makes sense. Thanks!

2022-08-26 15:08 UTC, anishasthana commented
We've pulled Adriana's changes into #257

2022-08-26 23:36 UTC, accorvin commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
We definitely need to change something around how this works - either what we’re probing or how the page behaves. Note: I don’t think we should make this change now, but note it as a deficiency and fix it in 1.17.

Right now, kfnbc functionality other than the spawner UI can be broken and we wouldn’t know about it.

2022-08-26 23:40 UTC, cfchase commented on deploy.sh
> +notebook_spawner_host=$(oc::wait::object::availability "oc get route rhods-dashboard -n $ODH_PROJECT -o jsonpath='{.spec.host}'$NOTEBOOK_SUFFIX'" 2 30 | tr -d "'")
It should be easy to add liveness probes to all the backend controllers so we aren't ever in this situatoin, shouldn't it?

2022-08-29 08:45 UTC, closed without merging

2022-08-29 08:45 UTC, atheo89 commented
These changes have been pulled into https://github.com/red-hat-data-services/odh-deployer/pull/257