[WIP] ISV CRS, CRD and on prem apps 4907
red-hat-data-services/odh-deployer pull request #260
Opened 2022-09-12 08:34 UTC by dlabaj

This PR contains the CRDS and CRs for odh dashboard.  Applications that are only needed for on prem are located in the app-on-prem folder.  Final step to be added is the to only deploy the on prem apps for on prem clusters.

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2022-09-14 18:18 UTC, DaoDaoNoCode commented on odh-dashboard/crds/odh-application-crd.yaml
> +                endPoint:
Change this to `endpoint`.

2022-09-15 13:47 UTC, dlabaj commented on odh-dashboard/crds/odh-application-crd.yaml
> +                endPoint:
done.

2022-09-16 12:57 UTC, DaoDaoNoCode requested changes
Could you check all the `-docs.yaml` file to make sure all the docs have `type` field under `spec` but not `metadata`?

2022-09-16 12:57 UTC, DaoDaoNoCode commented on odh-dashboard/apps-on-prem/openvino/openvino-docs.yaml
> +  type: how-to
Can you remove the `type` here into `spec`?

2022-09-16 17:01 UTC, dlabaj commented on odh-dashboard/apps-on-prem/openvino/openvino-docs.yaml
> +  type: how-to
done

2022-09-19 10:33 UTC, dlabaj commented on odh-dashboard/apps-on-prem/openvino/openvino-docs.yaml
> +  type: how-to
done.

2022-09-19 14:11 UTC, LaVLaS commented
> Is there a specific reason we have these manifests going into deployer instead of into odh-manifests?

There are some fields in the ODHApplication CRs that will be modified by odh-dashboard that we need to ignore when reconciled

2022-09-19 14:13 UTC, DaoDaoNoCode approved these changes
/lgtm

2022-09-19 15:48 UTC, VaishnaviHire commented
This change also requires updating roles fo `rhods-operator` Service Account, since we are accessing new apis like `console.openshift.io`, `dashboard.opendatahub.io` etc.
Deployer Log - [log.pdf](https://github.com/red-hat-data-services/odh-deployer/files/9600492/log.pdf)

We would also need to update uninstall logic in [operator](https://github.com/red-hat-data-services/opendatahub-operator/blob/master/pkg/controller/kfdef/kfdef_controller.go#L605) to make sure new CRDs get cleaned up.  @LaVLaS  I wonder if that can be avoided if the CRDs are deployed through odh-manifests ?

2022-09-20 14:02 UTC, DaoDaoNoCode commented on odh-dashboard/apps-on-prem/aikit/kustomization.yaml
> +- aikit-app.yaml
could you add a new line here?

2022-09-22 20:55 UTC, VaishnaviHire commented
> > Is there a specific reason we have these manifests going into deployer instead of into odh-manifests?
> 
> There are some fields in the ODHApplication CRs that will be modified by odh-dashboard that we need to ignore when reconciled

@LaVLaS  Following up on this, as discussed removing fields from the CR allows modifying them, given that they are not [required](https://github.com/red-hat-data-services/odh-deployer/blob/isv-and-4907/odh-dashboard/crds/odh-application-crd.yaml#L142) fields. I tested with `spec.internalRoute` field 

```
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
  annotations:
    kfctl.kubeflow.io/kfdef-instance: rhods-dashboard.redhat-ods-applications
    kubectl.kubernetes.io/last-applied-configuration: >
  name: jupyter
  namespace: redhat-ods-applications
  labels:
    app: rhods-dashboard
    app.kubernetes.io/part-of: rhods-dashboard
spec:
  img: >- <>
  getStartedLink: 'https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html'
  internalRoute: testValue
  displayName: Jupyter
  kfdefApplications:
    - odh-notebook-controller
    - notebook-images
  support: red hat
  provider: Jupyter
  docsLink: 'https://jupyter.org'
  quickStart: create-jupyter-notebook
```

The kfdef annotation is added, and the field retains the user specified value.

2022-09-23 08:49 UTC, bdattoma commented on deploy.sh
> +consoleBrand=$(oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.customization.brand}')
what makes the cluster "dedicated"? I've run this command on a OSD cluster, and it returns dedicated. But it should return sth for managed right? @dlabaj

2022-09-25 17:28 UTC, dlabaj commented on deploy.sh
> +consoleBrand=$(oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.customization.brand}')
OSD cluster would return dedicated.  Let me get you more information on this.

2022-09-26 08:59 UTC, bdattoma commented on deploy.sh
> +consoleBrand=$(oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.customization.brand}')
yeah but it should be the expectation right? i see in the next lines (89-90-91) that if we are under "dedicated" we show the on prem apps. But OSD should show the entire catalogue of ISVs

2022-09-26 11:55 UTC, dlabaj commented on deploy.sh
> +consoleBrand=$(oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.customization.brand}')
yes correct

2022-09-26 14:07 UTC, bdattoma commented on deploy.sh
> +# Get the brand to determine if it's a dedicated system
what would happen if this code runs on ROSA clusters? would it see the cluster as "dedicated" like OSD? 

I was wondering if this check might be done in a independent way from the cluster provider. For example, by setting a particolar value in RHODS operator (e.g., in a configmap or in the kfdef or whatever it can work) when using the Self-managed install script. 
In this way the check would be independent from the cloud provider. It would not break if new upcoming cloud providers work differently from current ones. 

@dlabaj @LaVLaS

2022-09-27 12:55 UTC, bdattoma commented
@dlabaj should RHODS/ODH operator reconcile the CRs which are installed with it, if any of them get deleted?

2022-09-27 14:01 UTC, bdattoma commented
@dlabaj there could be an issue with yaml formatting for some items like OpenVINO: 
from live build:
![image](https://user-images.githubusercontent.com/88311595/192547474-94994370-a537-4317-823a-f0236c0d1674.png)

expected:
![image](https://user-images.githubusercontent.com/88311595/192547609-db6cc640-5f80-4953-958e-fbfd105268b6.png)

2022-09-27 16:25 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
cannot we just upload the svg image with the operator?

2022-09-28 15:34 UTC, bdattoma commented on deploy.sh
> +# Get the brand to determine if it's a dedicated system
apparently this won't work on ROSA cluster, where the "brand" attribute is not set.

2022-09-28 16:05 UTC, dlabaj commented on odh-dashboard/apps-on-prem/aikit/kustomization.yaml
> +- aikit-app.yaml
Done

2022-09-28 16:07 UTC, dlabaj commented
> @dlabaj should RHODS/ODH operator reconcile the CRs which are installed with it, if any of them get deleted?

The operator won't reconcile them if they get deleted.

2022-09-28 16:08 UTC, dlabaj commented
> @dlabaj there could be an issue with yaml formatting for some items like OpenVINO: from live build: ![image](https://user-images.githubusercontent.com/88311595/192547474-94994370-a537-4317-823a-f0236c0d1674.png)
> 
> expected: ![image](https://user-images.githubusercontent.com/88311595/192547609-db6cc640-5f80-4953-958e-fbfd105268b6.png)

I'll look into the formatting issue.

2022-09-29 16:49 UTC, dlabaj commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
We could do that.  Can we create a bug for this issue.  We can fix it in 1.19

2022-09-30 03:58 UTC, LaVLaS commented
@dlabaj If `percept-labs` is being removed, you'll need to delete that folder and the reference to it in the apps-on-prem kustomization.yaml file

2022-09-30 07:44 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
we'll need to provide instructions to ISVs about creating their document resources, so I'm just asking because I wonder if they would be able to load a svg image directly instead of puttign the svg defintion. Would it work?

2022-09-30 07:45 UTC, bdattoma commented
> > @dlabaj should RHODS/ODH operator reconcile the CRs which are installed with it, if any of them get deleted?
> 
> The operator won't reconcile them if they get deleted.

should the operator being self-healing? if yes, IMO these resources should be restored too.

2022-09-30 08:13 UTC, bdattoma commented
tested the new live build: http://quay.io/llasmith/rhods-operator-live-catalog:1.18.0-1

1) RHOSAK and Jupyter are missing the Official blue mark in Explore page
![image](https://user-images.githubusercontent.com/88311595/193223780-2a84a504-7b5c-4712-908b-b068a5dc1758.png)

2) code to check if RHODS is self-managed or Managed may not work on OSD/ROSA. I've run the piece of code on local and it looks like not recognizing the Managed installation. Works fine on self-managed installations

2022-10-03 20:14 UTC, dlabaj commented
@bdattoma I updated this PR and updated this code to fix the issues you found
https://github.com/opendatahub-io/odh-dashboard/pull/615

2022-10-06 04:36 UTC, LaVLaS commented on deploy.sh
> +# Get the brand to determine if it's a dedicated system
We decided to rely on the self-managed catalogsource name for this issue

2022-10-06 15:35 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
@dlabaj any final decision on this thread?

2022-10-06 15:37 UTC, bdattoma commented on odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml
> +    Go to [https://cloud.redhat.com/application-services/streams/kafkas](https://cloud.redhat.com/beta/application-services/streams/kafkas)
this must be changed to be consistent with GetStarted link `https://console.redhat.com/application-services/streams/kafkas` @dlabaj

2022-10-06 21:13 UTC, LaVLaS commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
@bdattoma The goal is to keep these dashboard CustomResources self-contained so that all of the information required for any dashboard tile can be referenced directly from the tile.  If we separate the image from the customResource then that is another point of failure, security concern, update process, ... for an asset that can be easily included in this resource

2022-10-07 08:01 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
ok @LaVLaS . But I see that the code has a mix of SVG code and image path. Is that expected?

2022-10-07 10:57 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-docs.yaml
> +  featureFlag: gpu-computing
this resource item is not appearing in the dashboard. Might be related to "featureFlag"? @dlabaj @LaVLaS

2022-10-07 11:02 UTC, bdattoma commented
text style is changed here wrt to v1.17.0-9 @dlabaj :

On the left you see the text for Resources item in v1.17.0-9, while on the right you see v1.18.0-3 (titles and other text labels look **bold**)
![image](https://user-images.githubusercontent.com/88311595/194538580-6537bee5-1410-4908-9d8d-a5554a3f987f.png)

2022-10-07 13:11 UTC, bdattoma commented on odh-dashboard/apps-on-prem/jupyter/jupyterhub-app.yaml
> +    opendatahub.io/categories: 'Model development,Model training,Notebook environments'
shoudl JH removed?

2022-10-10 09:21 UTC, bdattoma commented on odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml
> +    Go to [https://console.redhat.com/application-services/streams/kafkas](https://console.redhat.com/beta/application-services/streams/kafkas)
the latest live build provided (1.18.0-5) shows the old link [https://cloud.redhat.com/application-services/streams/kafkas](https://cloud.redhat.com/beta/application-services/streams/kafkas) @LaVLaS @dlabaj

2022-10-10 14:29 UTC, dlabaj commented
> text style is changed here wrt to v1.17.0-9 @dlabaj :
> 
> On the left you see the text for Resources item in v1.17.0-9, while on the right you see v1.18.0-3 (titles and other text labels look **bold**) ![image](https://user-images.githubusercontent.com/88311595/194538580-6537bee5-1410-4908-9d8d-a5554a3f987f.png)

We upgraded patternfly this is the new look.

2022-10-10 16:10 UTC, LaVLaS commented on odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml
> +    Go to [https://console.redhat.com/application-services/streams/kafkas](https://console.redhat.com/beta/application-services/streams/kafkas)
Apologies.  That `odh-deployer` image was built from a branch was last updated when #265 merged.  I pushed the updated `1.18.0-5` image that includes this change

2022-10-10 16:28 UTC, bdattoma commented on odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml
> +    Go to [https://console.redhat.com/application-services/streams/kafkas](https://console.redhat.com/beta/application-services/streams/kafkas)
thanks! :)

2022-10-10 16:29 UTC, bdattoma commented on odh-dashboard/apps-on-prem/jupyter/jupyterhub-app.yaml
> +    opendatahub.io/categories: 'Model development,Model training,Notebook environments'
@dlabaj @LaVLaS

2022-10-10 16:34 UTC, LaVLaS commented on odh-dashboard/apps-on-prem/jupyter/jupyterhub-app.yaml
> +    opendatahub.io/categories: 'Model development,Model training,Notebook environments'
This was automatically included in the sync of odh-dashboard applications from upstream but it will be removed in the next release.  Right now, it will never be displayed to the user when `jupyterhub` is disabled as a dashboard application

2022-10-10 16:40 UTC, bdattoma commented on odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
> +      <path class="st0" d="M37.3,37.6C37.3,37.4,37.3,37.4,37.3,37.6c-2.9,0-5.7,0.2-8.6,0.4c0.4,2.9,0.8,5.7,1.6,8.6
@dlabaj @LaVLaS

2022-10-10 19:16 UTC, dlabaj commented
Follow up issues for 1.19:
Refactor code to have CRDs in the manifest repo - https://github.com/red-hat-data-services/odh-deployer/issues/267
Dashboard update to not use embedded issues - https://github.com/opendatahub-io/odh-dashboard/issues/646

2022-10-10 20:02 UTC, LaVLaS commented
/approve

2022-10-10 20:22 UTC, merged