Delete CUDA buildchain from RHODS deployer
red-hat-data-services/odh-deployer pull request #275
Opened 2022-11-10 08:08 UTC by atheo89

Delete CUDA build chain from RHODS deployer

## Description
This PR deletes the CUDA build chain code from odh-deployer repository. The new pre-build images now are going to be loaded into RHODS through ImageStreams objects that will be located `jupyterhub/notebooks/overlays/additional` on odh-manifests repository. The corresponding PR is [here](https://github.com/red-hat-data-services/odh-manifests/pull/263)   

Files that deleted:
- buildchain.sh
- nbc/cuda-11.4.2/manifests.yaml
- From prometheus-configs.yaml (on the 'alerting.rules' section deleted the part of build alerts)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-5336
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2022-11-10 09:52 UTC, anishasthana requested changes
Is there a corresponding rhods-live-builder PR yet for the dockerfile updates?

2022-11-10 09:52 UTC, anishasthana commented on deploy.sh
> +# If buildconfigs with label rhods/buildchain=cuda-* found, delete them (replaced by pre-uild notebooks).
is `pre-uild` a typo?

2022-11-10 09:52 UTC, anishasthana commented on deploy.sh
> -$HOME/buildchain.sh
We should remove this from the dockerfile as well: https://github.com/red-hat-data-services/odh-deployer/blob/main/Dockerfile#L27

2022-11-10 09:52 UTC, anishasthana commented on deploy.sh
> -$HOME/buildchain.sh
We will also need to remove https://github.com/red-hat-data-services/odh-deployer/blob/main/Dockerfile#L40 right?

2022-11-10 12:10 UTC, atheo89 commented on deploy.sh
> +# If buildconfigs with label rhods/buildchain=cuda-* found, delete them (replaced by pre-uild notebooks).
yep!

2022-11-10 12:10 UTC, atheo89 commented
/hold WIP

2022-11-10 12:12 UTC, atheo89 commented
> Is there a corresponding rhods-live-builder PR yet for the dockerfile updates?

Not Yet, I am working on it, I will update all the correspond PR with it when it will be ready

2022-11-10 16:14 UTC, atheo89 commented
/unhold

2022-11-10 17:23 UTC, anishasthana commented on Dockerfile
>  ADD consolelink $HOME/consolelink
We will need to remove the following line too right? 
`ADD nbc $HOME/nbc`

2022-11-16 17:04 UTC, samuelvl commented on deploy.sh
> +# If buildconfigs with label rhods/buildchain=cuda-* found, delete them (replaced by pre-build notebooks).
```suggestion
# TODO: Remove in 1.21
# If buildconfigs with label rhods/buildchain=cuda-* found, delete them (replaced by pre-build notebooks).
```

2022-11-16 17:04 UTC, samuelvl commented on deploy.sh
> +# If imagestreams with label rhods/buildchain=cuda-* found, delete them (replaced by pre-build notebooks).
```suggestion
# TODO: Remove in 1.21
# If imagestreams with label rhods/buildchain=cuda-* found, delete them (replaced by pre-build notebooks).
```

2022-11-18 12:10 UTC, lugi0 commented
Tested the latest live build (quay.io/rh_ee_atheodor/rhods-operator-live-catalog:1.20.0-rhods-5336) and images are looking good (i.e. cuda is present), still in the process of going through all automated tests.

2022-11-18 12:57 UTC, samuelvl approved these changes
/lgtm

2022-11-18 13:08 UTC, merged