Draft: Add alerts for DSPO
red-hat-data-services/odh-deployer pull request #319
Opened 2023-04-05 16:58 UTC by DharmitD

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2023-04-05 17:21 UTC, DharmitD commented
This PR is blocked until https://github.com/red-hat-data-services/odh-deployer/pull/314 and https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/merge_requests/82 are merged. 
Once they're merged, this PR will be rebased and marked ready for review.

2023-04-14 15:23 UTC, DharmitD commented
> Remember to update the prometheus init-container (wait-for-deployment) in order to wait until the data science pipeline operator is active, or the alert will fire

Done, updated the prometheus init container.

2023-04-14 15:33 UTC, jgarciao commented
Same for is needed for blackbox-exporter's init container (I just saw it)

2023-04-14 18:40 UTC, harshad16 requested changes
Some changes are needed
Testing this further

2023-04-14 18:40 UTC, harshad16 commented on monitoring/prometheus/blackbox-exporter-common.yaml
> +              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
```suggestion
              if [ $mm_svc_exists = false ]; then exit 1; fi &&

              dspo_svc_exists=false &&
              for i in `seq 1 230`; do sleep 10; echo "Waiting for Data Science Pipelines Operator service to become available..."; if curl -sS -I http://data-science-pipelines-operator-service.redhat-ods-applications.svc:8080/metrics; then dspo_svc_exists=true; break; fi; done &&
              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
```

2023-04-14 18:40 UTC, harshad16 commented on monitoring/prometheus/prometheus-configs.yaml
> +>>>>>>> 3e9e7cc (Add alerts for DSPO)
```suggestion

```

2023-04-14 18:40 UTC, harshad16 commented on monitoring/prometheus/prometheus.yaml
> +              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
```suggestion
              if [ $mm_svc_exists = false ]; then exit 1; fi &&

              dspo_svc_exists=false &&
              for i in `seq 1 230`; do sleep 10; echo "Waiting for Data Science Pipelines Operator service to become available..."; if curl -sS -I http://data-science-pipelines-operator-service.redhat-ods-applications.svc:8080/metrics; then dspo_svc_exists=true; break; fi; done &&
              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
```

2023-04-14 19:13 UTC, DharmitD commented on monitoring/prometheus/prometheus.yaml
> +              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
Done, updated to have this change.

2023-04-14 19:13 UTC, DharmitD commented on monitoring/prometheus/prometheus-configs.yaml
> +>>>>>>> 3e9e7cc (Add alerts for DSPO)
Updated to remove this.

2023-04-14 19:13 UTC, DharmitD commented on monitoring/prometheus/blackbox-exporter-common.yaml
> +              if [ $dspo_svc_exists = false ]; then exit 1; fi; exit 0
Done, updated to have this change.

2023-04-14 19:23 UTC, harshad16 commented
Tested the changes :
The alerts fires info level alerts
![Screenshot from 2023-04-14 15-20-23](https://user-images.githubusercontent.com/14028058/232137409-37ed6bda-5da7-4c7b-ad77-050038a7e83b.png)
![Screenshot from 2023-04-14 15-20-11](https://user-images.githubusercontent.com/14028058/232137412-2083a29f-263e-4e2a-b264-ba849a3e3b60.png)

2023-04-14 19:25 UTC, harshad16 approved these changes
/lgtm

:+1:

2023-04-14 19:32 UTC, harshad16 requested changes
need one more change

2023-04-14 19:32 UTC, harshad16 commented on monitoring/prometheus/prometheus-configs.yaml
> +            sum(probe_success:burnrate30m{instance=~"data-science-pipelines-operatorr"}) by (instance) > (6.00 * (1-0.98000))
```suggestion
            sum(probe_success:burnrate30m{instance=~"data-science-pipelines-operator"}) by (instance) > (6.00 * (1-0.98000))
```

2023-04-14 19:35 UTC, DharmitD commented on monitoring/prometheus/prometheus-configs.yaml
> +            sum(probe_success:burnrate30m{instance=~"data-science-pipelines-operatorr"}) by (instance) > (6.00 * (1-0.98000))
Done!

2023-04-14 19:51 UTC, harshad16 commented
Retested with changes:

Waited for all 3 alerts to fire:
![Screenshot from 2023-04-14 15-48-10](https://user-images.githubusercontent.com/14028058/232141890-a64d986d-9335-4dbe-8a18-36646b6cdfd4.png)
![Screenshot from 2023-04-14 15-47-44](https://user-images.githubusercontent.com/14028058/232141893-c32752fe-fa77-46fa-a6aa-df99f70f4eb0.png)


Process for testing:

After applying the rules.
Scale down the service.
Alerts started firing.

/lgtm

2023-04-14 19:54 UTC, HumairAK commented
/approve

2023-04-14 19:55 UTC, HumairAK commented
From @jgarciao : 

> "If you are confident with PR319 and merge it, it will be included in a pre RC build DevOps will create on Monday (so I'll be able to test that with all the changes)" ~ Jorge


/label qe-approved

2023-04-14 19:59 UTC, harshad16 approved these changes
/lgtm

2023-04-14 20:04 UTC, merged