Remove getting OVMS image from the CSV, use the one defined in the servingruntime instead
red-hat-data-services/odh-deployer pull request #327
Opened 2023-04-14 16:07 UTC by Xaenalt

With the change to the quay.io image, we can the logic for getting this from the CSV

This is related to https://github.com/red-hat-data-services/odh-manifests/pull/328

## Description

## How Has This Been Tested?

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): 
- [X] The Jira story is acked.
- [ ] Live build image: 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2023-04-14 17:05 UTC, lucferbux commented
We still ned this right? I assume sha of that related image could change between versions, hence we need to update it when upgrading the operator right?

And this logic will change in model serving v2.

2023-04-15 06:43 UTC, zdtsw approved these changes
/hold

2023-04-17 06:46 UTC, lucferbux requested changes

2023-04-17 06:46 UTC, lucferbux commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
I'm sorry, I still don't understand this change, why would we want to harcode the value here? Is it not present in the csv too? https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/blob/rhods-1.26-rhel-8/distgit/containers/odh-operator-bundle/bundle-template/manifests/rhods-operator.clusterserviceversion.yml#L667

that would mean that we should update it every time there's a rebuild, who would be in charge of that?

I'm still not sure why we want to change this logic.

2023-04-17 06:46 UTC, lucferbux commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
@zdtsw you might be able to answer this question, I'm sorry I don't have the hole context here

2023-04-17 06:48 UTC, lucferbux requested changes

2023-04-17 06:48 UTC, lucferbux commented on kfdefs/rhods-model-mesh.yaml
> -        - name: odh-openvino
And why are we removing this? Isn't openivno a related image still?

2023-04-17 06:58 UTC, zdtsw commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
right.
so my understanding:

1) openvino image is unlikely to change in a frequent fashion. (i.e maybe several months we will build a new openvino image by openshift-ci) so if we hard code digest , it is not that often we need to update it. 

2) the reason why hard code it and set to `openvino_img=` is to not set the RELATED_IMAGE_* variable in CSV file.
and only add openvino pullspec (hardcode one) in the CSV ` spec.annotation`s and let the build system to auto generate and inject it into `relatedImages` 

But after last Friday, some internal discussion of how our build system works.
I think the solution to get it into annotations wont work as well, due to the fact where openvino image lives. 

so we need to hold this PR for a while, till we find a way that works with build and follow that direction to change our solution in deploy and CSV and so on.

2023-04-17 06:58 UTC, zdtsw reviewed
lets wait a bit till more clear how it can work with our build

2023-04-17 14:18 UTC, Xaenalt commented on kfdefs/rhods-model-mesh.yaml
> -        - name: odh-openvino
No, the goal is to move this out of related images, since CPaaS won't let us use a quay image in that field

2023-04-17 14:18 UTC, Xaenalt commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
Correct, the reason we're moving it is that CPaaS has a check in the relatedImages field to prevent non-approved image repos, which quay is not one of those. They're reluctant to add quay because of the implications system-wide, so this ends up being the only way

2023-04-17 14:32 UTC, Xaenalt commented
@LaVLaS @VaishnaviHire PTAL

2023-04-17 14:45 UTC, VaishnaviHire commented
/lgtm 

Given the entry under the [CSV](https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/blob/rhods-1.26-rhel-8/distgit/containers/odh-operator-bundle/bundle-template/manifests/rhods-operator.clusterserviceversion.yml#L667) is removed

2023-04-17 14:47 UTC, VaishnaviHire approved these changes

2023-04-17 14:54 UTC, VaishnaviHire commented
/label qe-approved

2023-04-17 14:56 UTC, Jooho commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
The best way is... put this value in one place and use it everywhere like before. Sha in CSV and other components use it from CSV. But CPaaS does not like quay.io so we need to find another place but I couldn't find a good place. So for now, hard coded would be good to go but we need to revisit this.
For your information, this is the reason why we can not put NOTEBOOK sha into CSV. please refer this for notebook @VaishnaviHire  Last time, I heard you have the plan to put NOTEBOOK sha into environmental variables in the CSV. But CPaaS does not allow it.

2023-04-17 14:56 UTC, Jooho commented on kfdefs/rhods-model-mesh.yaml
> -        - name: odh-openvino
CPaaS does not allow to add quay.io image into it. We need to update disconnected installation official doc as well.

2023-04-17 14:56 UTC, Jooho approved these changes
/lgtm

2023-04-17 14:57 UTC, VaishnaviHire commented
/cherry-pick rhods-1.26

2023-04-17 14:58 UTC, Jooho commented
@Xaenalt It needs to update a doc for disconnected installation. Could you please check this as well?

2023-04-17 14:58 UTC, Xaenalt commented
@Jooho Yeah, I'll add a ping in the JIRA about it to the docs team

2023-04-17 14:59 UTC, LaVLaS commented
/cherry-pick rhods-1.26

2023-04-17 15:02 UTC, lucferbux commented on deploy.sh
> +  openvino_img='quay.io/modh/openvino-model-server@sha256:c89f76386bc8b59f0748cf173868e5beef21ac7d2f78dada69089c4d37c44116'
Ok, great, bear in mind this will change with model serving v2, I suggest we should add this into the default ovms runtime object once we have it, thanks all for the update, I didn't have the context.

2023-04-17 15:02 UTC, lucferbux approved these changes

2023-04-17 15:06 UTC, merged