Fix Prometheus data source secret generation
red-hat-data-services/odh-deployer pull request #33
Opened 2021-02-18 20:02 UTC by anishasthana

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

2021-02-18 20:27 UTC, crobby approved these changes
works for me, the secret seems to be created correctly

2021-02-18 21:39 UTC, crobby commented on monitoring/grafana-dashboards/jupyterhub-slis.configmap.yaml
> +                    "legendFormat": "Jupyterhuv Server Spawn Success Rate",
Jupyterhuv??? :)

2021-02-18 21:42 UTC, crobby requested changes
Probably just the one jupyterhuv type-o

2021-02-18 22:04 UTC, anishasthana commented on monitoring/grafana-dashboards/jupyterhub-slis.configmap.yaml
> +                    "legendFormat": "Jupyterhuv Server Spawn Success Rate",
arghhh

2021-02-18 22:06 UTC, anishasthana commented on monitoring/grafana-dashboards/jupyterhub-slis.configmap.yaml
> +                    "legendFormat": "Jupyterhuv Server Spawn Success Rate",
fixed

2021-02-19 11:59 UTC, crobby approved these changes
appears to be working for me; lgtm

2021-02-19 11:59 UTC, merged