Add an alert for detecting stuck deployment rollouts
red-hat-data-services/odh-deployer pull request #334
Opened 2023-05-02 09:31 UTC by VannTen

## Description

Alerts of deployment not progressing (whatever the reason) for ODH controllers.

## Merge criteria:

- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-8152
- [x] Live build image: quay.io/modh/rhods-operator-live-catalog:1.27.0-rhods-8152
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2023-05-02 19:15 UTC, anishasthana requested changes

2023-05-02 19:15 UTC, anishasthana commented on monitoring/prometheus/prometheus-configs.yaml
> +          expr: sum(kube_deployment_status_condition{condition="Progressing", status="false"}) by (deployment) != 0
Won't we need to filter these to only alert for RHODS pods?

2023-05-02 19:15 UTC, anishasthana commented on monitoring/prometheus/prometheus-configs.yaml
> +            summary: An ODH controller deployment upgrade is stuck.
Should say RHODS :-)

2023-05-03 09:07 UTC, VannTen commented on monitoring/prometheus/prometheus-configs.yaml
> +          expr: sum(kube_deployment_status_condition{condition="Progressing", status="false"}) by (deployment) != 0
Maybe, I have a bit of doubt about that:
- This rules are against the prometheus instance shipped by RHODS, right ? -> in that case I'd rather filter directly in the collect job which takes those metrics from the cluster-prometheus.
- If not, we can just filter by namespace: `{namespace~='redhat-ods-applications|<etc>}`

2023-05-09 12:37 UTC, VannTen commented
See kubernetes-monitoring/kubernetes-mixin#845 for a potential more general alternative.

2023-05-29 08:44 UTC, VannTen commented
/close
(as the upstream PR was merged, it will flow down into openshift eventually)

2023-05-29 08:44 UTC, closed without merging