Add Habana tiles
red-hat-data-services/odh-deployer pull request #371
Opened 2023-07-26 17:59 UTC by chen-levkovich

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

2023-07-27 07:41 UTC, lucferbux requested changes
I'm gonna deploy it later to my cluster and I'll add screenshot so you can take a look @chen-levkovich 

In the meantime, I've spotted an issue, you need to add this newly created folder in the this kustomize file https://github.com/red-hat-data-services/odh-deployer/blob/main/odh-dashboard/apps/kustomization.yaml

2023-07-27 07:43 UTC, lucferbux commented
Btw @zdtsw if we are doing some efforts to migrate ISV to odh-manifest, we should move the contribution files and so to have docs for external contributors who wants to add new info right?

2023-07-27 08:28 UTC, zdtsw commented
> Btw @zdtsw if we are doing some efforts to migrate ISV to odh-manifest, we should move the contribution files and so to have docs for external contributors who wants to add new info right?

I think the final goal is to not use "odh-deployer" for ISV. 
Till new operator is stable, we still need make the double efforts to keep add/update ISV in odh-deployer (i.e for Habana) and sync such into odh-manifasts. 
But for the current/ongoing release, I do not think the plan is to have Habana for new operator (just to mitigate risk from too much integration work)

2023-07-27 13:53 UTC, harshad16 commented
/hold 

Holding the PR for getting some clarity on this inclusion.
@chen-levkovich  could please include the description.

2023-07-27 16:12 UTC, chen-levkovich commented
What description should I include?

2023-07-28 08:37 UTC, lucferbux requested changes

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +apiVersion: console.openshift.io/v1
This is the actual output:

```bash
The OdhQuickStart "pytorch-tutorial-habana-ai" is invalid: 
* spec.tasks[0].summary.failed: Required value
* spec.tasks[0].summary.success: Required value
* spec.tasks[0].review.instructions: Invalid value: "": spec.tasks[0].review.instructions in body should be at least 1 chars long
* spec.tasks[1].summary.success: Required value
* spec.tasks[1].review.instructions: Invalid value: "": spec.tasks[1].review.instructions in body should be at least 1 chars long
* spec.tasks[2].review.instructions: Invalid value: "": spec.tasks[2].review.instructions in body should be at least 1 chars long
* spec.tasks[2].summary.success: Required value
```

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana_kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
This file should be name just `kustomization`

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        success:
You need succcess or remove the field

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        success:
And here too

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        instructions: |-
You need some value here

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        instructions: |-
Same here

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        success:
Same here

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-app.yaml
> +apiVersion: dashboard.opendatahub.io/v1
You'll need to add this

`  - ./habana`

At the end of `oah-dashboard/apps/kustomization.yaml`

2023-07-28 08:37 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        instructions: |-
And here too

2023-07-28 08:37 UTC, lucferbux commented
@chen-levkovich here you have a few screenshots:
<img width="2250" alt="Screenshot 2023-07-28 at 10 37 17" src="https://github.com/red-hat-data-services/odh-deployer/assets/16117276/4e6210e8-09c0-4195-9dda-7d5c4df341fc">
<img width="2177" alt="Screenshot 2023-07-28 at 10 36 59" src="https://github.com/red-hat-data-services/odh-deployer/assets/16117276/2f391d40-731a-4189-8a4c-8103c639513a">

2023-07-28 08:40 UTC, lucferbux commented
btw @taneem-ibrahim @Jooho 

Can you kindly take over this? I'm still not sure who I need to contact regarding this kind of situations. We are always willing to help here, but I would love to know the actual flow to be more efficient the next time.

Thanks in advance.

2023-09-05 10:35 UTC, lucferbux requested changes
There's only one change left, I've applied the suggestions I'm asking bellow and with that you can see that is working:

<img width="2243" alt="Screenshot 2023-09-05 at 12 34 22" src="https://github.com/red-hat-data-services/odh-deployer/assets/16117276/687d85af-23fc-4643-b38e-199f1d4fcd7d">

2023-09-05 10:35 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        failedTaskHelp: This task is not verified yet. Try the task again.
You still need the `instructions` attribute, try something like this:

```suggestion
        instructions: |-
          #### Verify the file is created:
          Do you have a file called `example.py`?
        failedTaskHelp: This task is not verified yet. Try the task again.
```

2023-09-05 10:35 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +        failedTaskHelp: This task is not verified yet. Try the task again.
Same here, try to add something like this:

```suggestion
        instructions: |-
          #### Verify the lines are present in the file:
          Do you have the lines in the file?
        failedTaskHelp: This task is not verified yet. Try the task again.
```

2023-09-05 10:35 UTC, lucferbux commented on odh-dashboard/apps/habana/habana-quickstart.yaml
> +          This task is not verified yet. Try the task again.
And finally here:

```suggestion
        instructions: |-
          #### Verify the output is as expected:
          Do you see the expected output?
        failedTaskHelp:
          This task is not verified yet. Try the task again.
```

2024-02-21 07:30 UTC, zdtsw commented
@lucferbux can we close this one if the change has been merged into odh-dashboard?

2024-02-28 12:41 UTC, lucferbux commented
It came on hold, I'm not sure if @chen-levkovich wanted to continue with the introduction of the habana tile

2024-07-23 09:23 UTC, closed without merging