Add slo alerts
red-hat-data-services/odh-deployer pull request #78
Opened 2021-04-05 18:39 UTC by anishasthana

cc @hemajv

2021-04-05 18:40 UTC, anishasthana commented
I'd like reviews from all 3 of you on this PR. I'd recommend first looking at this PR commit by commit, and then as a whole. Please review this one carefully, there's a ton of yaml and promql here, and I'd hate for some logic error to slip by.

2021-04-06 14:42 UTC, 4n4nd requested changes
one small change, but other than that looks good to me :+1:

2021-04-06 14:42 UTC, 4n4nd commented on monitoring/jupyterhub-db-probe/src/main.py
>          return (-1)
@anishasthana I think this should be returning a `0` instead of `-1`, I think this is how a "down" service is usually denoted in Prom metrics.

2021-04-06 14:43 UTC, anishasthana commented on monitoring/jupyterhub-db-probe/src/main.py
>          return (-1)
Good catch. I forgot to update this when I updated the other expression

2021-04-06 15:16 UTC, hemajv commented on monitoring/prometheus/prometheus.yaml
> +          for: 2m
just curious , what was the reasoning behind the various `expr` combinations? i.e. alerting on burn rates of `5m and 1h`, `30m and 6h` etc and how are the thresholds determined?

2021-04-06 16:23 UTC, anishasthana commented on monitoring/prometheus/prometheus.yaml
> +          for: 2m
Based it on https://promtools.dev/alerts/ and the Google SRE book. The slo promtool was super valuable in going from the tables in the book to actual promql

2021-04-06 16:34 UTC, hemajv commented on monitoring/prometheus/prometheus.yaml
> +          for: 2m
ah I see, the slo promtool looks pretty neat! :smiley:

2021-04-06 16:35 UTC, hemajv commented
lgtm! :ship:

2021-04-08 17:52 UTC, maulikjs approved these changes

2021-04-08 17:54 UTC, merged