Add Anaconda CE manifest and secret
red-hat-data-services/odh-deployer pull request #88
Opened 2021-04-19 16:12 UTC by Xaenalt

2021-04-19 16:31 UTC, cfchase requested changes

2021-04-19 16:31 UTC, cfchase commented on opendatahub.yaml
> +    name: odh-dashboard
I don't think this should have the same name as the odh-dashboard

2021-04-19 17:17 UTC, crobby requested changes
You're going to need to change the Dockerfile to include the "partners" subdir

2021-04-19 17:37 UTC, Xaenalt commented
Added

2021-04-20 19:08 UTC, crobby approved these changes
lgtm

2021-04-20 19:16 UTC, anishasthana requested changes
@Xaenalt Can you squash the commits?

2021-04-20 19:24 UTC, anishasthana approved these changes
/lgtm

2021-04-20 20:05 UTC, cfchase approved these changes

2021-04-21 16:21 UTC, crobby approved these changes
I have tested this along with the manifest change and the dashboard change.  I think we're in good shape.

2021-04-21 16:21 UTC, merged