WIP: Move monitoring to odh-manifests
red-hat-data-services/odh-deployer pull request #95
Opened 2021-05-20 17:29 UTC by mroman-redhat

Moving monitoring components to odh-manifests to solve jira issue 701

2021-05-21 13:21 UTC, anishasthana approved these changes
This set of changes looks good. I vote we update the odh-manifests PR as well and then merge this in.

2021-05-21 13:21 UTC, anishasthana commented on deploy.sh
>  oc new-project $ODH_MONITORING_PROJECT || echo "INFO: $ODH_MONITORING_PROJECT project already exists."
We will still need the project creation

2021-05-27 16:25 UTC, crobby commented on rhods-monitoring.yaml
> +
Extra newline here??

2021-05-27 16:27 UTC, crobby commented
I think this looks pretty good.  As part of this, we probably need some way to either communicate to QE or provide PRs to their test repos for the cleanup of the monitoring KfDef.  (I will also need to update my script)
We might also need to update some of our documentations to reflect the new reality.

2021-05-27 16:27 UTC, crobby approved these changes

2021-05-27 17:44 UTC, crobby commented on rhods-monitoring.yaml
> +  name: redhat-ods-monitoring
Maybe just "monitoring" so the object name isn't confused with the namespace??

2021-05-27 17:50 UTC, crobby commented on rhods-monitoring.yaml
> +    uri: https://github.com/mroman-redhat/odh-manifests/tarball/move-monitoring
this also needs to change before we can merge

2021-05-27 17:51 UTC, crobby requested changes
need to reference the "local" manifests in the operator

2021-06-01 15:27 UTC, anishasthana reviewed
Changes look good but I haven't been able to test it out yet. @mroman-redhat  is this deployed anywhere?

2021-06-01 16:15 UTC, mroman-redhat commented
> Changes look good but I haven't been able to test it out yet. @mroman-redhat is this deployed anywhere?

This should be it https://console-openshift-console.apps.mroman.dev.datahub.redhat.com/k8s/ns/redhat-ods-operator/pods

2021-06-01 17:32 UTC, anishasthana commented
Hmm, I deleted the `rhods-rules` prometheus rule but the operator still hasn't recreated it.

2021-06-01 18:17 UTC, crobby approved these changes

2021-06-01 18:18 UTC, crobby approved these changes
I'm good with these changes.

2021-06-01 18:19 UTC, crobby commented
> Hmm, I deleted the `rhods-rules` prometheus rule but the operator still hasn't recreated it.

Is this behavior different from the experience before?

2021-06-01 18:39 UTC, anishasthana commented
Weirdly enough, it seems like it _did_ eventually reconcile. It just took something like an hour to do so.

2021-06-01 19:54 UTC, merged